# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edaa9377ed58f117a47dc711fe60c4297462b2f4d40d63df439f5feb6d4a5a112368b0e73ebcac424388f382d4a0e3864bdc22f7b99f63ab4b8735a2ab4dd697

test:
  secret_key_base: d1c04d9920128a7cced6f5f08e3c28333f9bb27a6edda0a9e9f7bc3444bd12fd928c85d10d7383c7fc4e323b87b0902a91a45f48f86079527460dcc763c6c881

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
